name: Continuous Integration with Github Actions

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven

    - name: Build Application JAR
      working-directory: ./rest-with-spring-boot-and-java/rest-with-spring-boot-and-java/
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: ./rest-with-spring-boot-and-java/rest-with-spring-boot-and-java/
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/rest-with-springboot-and-java:${{github.run_id}} .

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:latest ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:latest
